# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be112e5ae5b6a4acc98446d3074fc7d66972fd3b0924443baab76cd11fe6b1448b6ce2caa5b93ca90354ccae5a79ca2f684e355425cb3f2cb78b7f31717fa75f

test:
  secret_key_base: d52a5fc27dbe0715b0ec06d14b9157cc5068dd8baf79fef54abbc96dbbe6ceb6de80cd0c85213642a72bbbce7f7034c063752b0e09c860053b038d0a4c25e3ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
